### ISSUE TITLE
[Bug]: Can't play Video when connected over Tailscale 

### ISSUE THREAD

**Issue by chemicalsam** [streamyfin/streamyfin#278]
### What happened?

Video won't play or allow fast forwarding when using Jellyfin remote access through tail scale. It will play through the standard/old Jellyfin app, But not streamyfin or Swiftfin

### Reproduction steps

1. Connect to tailscale VPN 
2. Open streamyfin 
3. Press play on movie 

### Which device and operating system are you using?

iPhone 16 Pro Max 18.1.1

### Version

0.22.0

**Comment by fredrikburmester** [comment]
Hmm, I can play fine over Tailscale. Could you add a screen recording maybe? This might be a VLC issue since both Streamyfin and Swiftfin uses it, while the standard Jf app doesn't.

**Comment by chemicalsam** [comment]
https://imgur.com/a/E4tn6Kq

I’ve uploaded a screen recording here. So it’s a bit odd because it can play smaller files such as a show but when you try to resume a movie it doesn’t play. Am I not waiting long enough for it to buffer? It does seem to take an awfully long time- I know it should take longer going through tailscale but this seems a bit extreme.

**Comment by chemicalsam** [comment]
I have an update, if I change the player to native from swiftfin on Swiftfin iOS app it plays through tailscale just fine but not on the swiftfin player. I don't see this as a setting on Streamyfin however, I am not sure why this would be an issue on Jellyfins side.

**Comment by fredrikburmester** [comment]
How do you have Tailscale set up? Are you using the exit node method or none?

**Comment by boimouseorange** [comment]
Has anybody had an issue connecting to their Jellyfin server through Tailscale using Streamyfin?

P.S. I can connect through Tailscale with no issues through other clients. The only one I’m having trouble with is Streamyfin.

**Comment by xpire** [comment]
I'm using Tailscale to connect to expose jellyfin to all my devices, and I don't seem to have this issue and can play videos fine through streamyfin. Videos play faster on streamyfin compared to swiftfin as I can lower the bitrate.

Maybe you should experiment with playing at a lower bitrate to confirm if it's a bandwidth issue. (Assuming you have a cpu that supports transcoding or a gpu).

**Comment by boimouseorange** [comment]
> I'm using Tailscale to connect to expose jellyfin to all my devices, and I don't seem to have this issue and can play videos fine through streamyfin. Videos play faster on streamyfin compared to swiftfin as I can lower the bitrate.
> 
> Maybe you should experiment with playing at a lower bitrate to confirm if it's a bandwidth issue. (Assuming you have a cpu that supports transcoding or a gpu).

I was able to connect once I left the State I was in. No idea how that worked but I got it working.

**Comment by Stetsed** [comment]
I'm going to go ahead and have this issue closed as I wasn't able to recreate it in any of my test scenarios, and it seems like you where able to get it to work. If such an issue pops up again this may be reopened.

**Comment by vodium-vastro** [comment]
I'm seeing the exact same scenario. I'm using Tailscale + Traefik + Jellyfin. 

I am able to fully browse the library, but playback is a black background with a spinner. I see the same thing with Swiftfin unless I use the native player. Using Infuse, I have no issues at all and playback is fine.

If I download the same movie for offline, I can then go in to downloads and watch the video just fine.

**Comment by flo1t** [comment]
> I'm seeing the exact same scenario. I'm using Tailscale + Traefik + Jellyfin.
> 
> I am able to fully browse the library, but playback is a black background with a spinner. I see the same thing with Swiftfin unless I use the native player. Using Infuse, I have no issues at all and playback is fine.
> 
> If I download the same movie for offline, I can then go in to downloads and watch the video just fine.

i had to add curve X25519 (or CurveP256) to the curvePreferences (tls options) to be able to stream via traefik.

**Comment by vodium-vastro** [comment]
@flo1t Thats amazing, thank you, that worked. For other people, this is what I used in the end. I was unable to get it to work with modern/tls 1.3 despite adding the `curvePreferences` section to it.

In my dynamic config (see under `intermediate`):

```yaml
tls:
  options:
    modern:
      minVersion: VersionTLS13
      sniStrict: true
      curvePreferences:
        - X25519
        - CurveP256
        - CurveP384

    intermediate:
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      minVersion: "VersionTLS12"
      sniStrict: true
      curvePreferences:
        - X25519
        - CurveP256
        - CurveP384
```

Then in my jellyfin docker-compose.yml

```yaml
...
labels:
      - traefik.enable=true
      ...
      - traefik.http.routers.jellyfin-https.tls.options=intermediate@file
...
```

If anyone has a working TLS 1.3 config, please let me know.

The configs are based on [Modern](https://ssl-config.mozilla.org/#server=traefik&version=3.2.1&config=modern&guideline=5.7) and [Intermediate](https://ssl-config.mozilla.org/#server=traefik&version=3.2.1&config=intermediate&guideline=5.7) from https://ssl-config.mozilla.org
