### ISSUE TITLE
Feat: Allow customising homescreen

### ISSUE THREAD

**Issue by lostb1t** [streamyfin/streamyfin#418]
I want to be able to customize my homescreen with custom media rows and styling

I want to be able to manage this through the centralised plugin. Managing it through the app is not part of this feature request 

example config

```

home:
  sections:
    Trending:
      style: portrait
      type: row 
      items:
        args: 
          sortBy: AddedDate
          sortOrder: Ascending
          filterByGenre: [""Anime"", ""Comics""]";
```
